---
collections:
  - name: redhat.rhel_system_roles
    source: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  
  - name: redhatinsights.insights
    source: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/

  - name: microsoft.sql
    source: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/

  - name: community.vmware
    source: https://aap-pah1.ekeberg.io/api/galaxy/content/community/

  - name: redhat.insights
    source: https://aap-pah.ekeberg.io/api/galaxy/content/rh-certified/
