---
collections:
  - name: redhat.rhel_system_roles
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  - name: redhatinsights.insights
  - name: microsoft.sql
  - name: community.vmw
  - name: redhat.insights
