---
collections:
  - name: vmware.vmware_rest
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  - name: microsoft.sql
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  - name: redhatinsights.insights
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  - name: redhat.rhel_system_roles
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  - name: community.vmw
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/community/

