---
---
- name: "Install System Role for Web Console"
  hosts: "{{ vm_name }}"
  become: yes


  tasks:
    - name: Install RHEL Web Console (Cockpit)
      include_role:
        name: redhat.rhel_system_roles.cockpit
      vars:
        cockpit_packages: default
        #cockpit_packages: minimal
        #cockpit_packages: full
        cockpit_enabled: yes
        cockpit_started: yes

    - name: Configure Firewall for Web Console
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
