---
- name: Post configuration of VM
  hosts: "{{ vm_name }}"
  become: true

  tasks:
    - name: Install necessary packages
      ansible.builtin.package:
        name:
          - rhc-worker-playbook
        state: latest

    - name: Register with rhc
      ansible.builtin.shell: |-
        rhc connect 

        expect "User:"
        send "{{ rhsm_username }}\n"

        expect "Password:"
        send "{{ rhsm_password }}\n"

        exit 0
