---
- name: Setup a central metrics server with grafana and pcp
  hosts: "{{ vm_name }}"
  collections:
    - redhat.rhel_system_roles
  become: true

  tasks:
    - name: Open Firewall for grafana
      ansible.posix.firewalld:
        service: grafana
        permanent: true
        immediate: true
        state: enabled
