---
- name: Install System Role for Web Console
  hosts: "{{ vm_name }}"
  become: true

  tasks:
    - name: Install RHEL Web Console (Cockpit)
      vars:
        cockpit_packages: default
        cockpit_enabled: true
        cockpit_started: true
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.cockpit

    - name: Open Firewall for Web Console
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        immediate: true
        state: enabled
