---
- name: Post configuration of VM
  hosts: "{{ vm_name }}"
  collections:
    - redhatinsights.insights
  become: true

  tasks:
    - name: Register with Red Hat insights
      redhatinsights.insights.insights_register:
        state: present
