---
- name: Solve prereqs for sql installation on the host
  hosts: "{{ vm_name }}"
  become: true

  tasks:
    - name: Permit mssql traffic in fw on port 1433/tcp
      ansible.posix.firewalld:
        port: 1433/tcp
        permanent: true
        immediate: true
        state: enabled

    - name: Permit monitoring traffic
      with_items:
        - pmcd
        - pmproxy
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
