---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vcenter_hostname: 
    vcenter_username: 
    vcenter_password: 
    vcenter_validate_certs: false
    template_name: 
    vm_name: 
    vm_folder: 
    vm_resource_pool:
    vm_datastore:
    vm_cluster:
    vm_memory_mb:
    vm_cpu_count:
    vm_disk_gb:

  tasks:
    - name: Use AAP VMware credentials
      ansible.builtin.set_fact:
        vcenter_hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        api_user: '{{ lookup("env", "VMWARE_USER") }}'
        api_pass: '{{ lookup("env", "VMWARE_PASSWORD") }}'

    - name: Clone VM Template
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_password: "{{ api_pass }}"
        vcenter_username: "{{ api_user }}"
        placement:
          cluster: "{{ vm_cluster }}"
          datastore: "{{ vm_datacenter }}"
          folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        source: "{{ template_name }}"
        cpu:
          hot_add_enabled: true
          count: "{{ vm_cpu }}"
        memory:
          hot_add_enable: true
          size_MiB: "{{ vm_memory }}"
        disks:
          - size_gb: "{{ vm_disk_size }}"
            type: default
        
        guest_customization_spec: "{{ vm_customization_spec }}"
        state: present
      register: vm_name

    - name: Wait until my VM is ready
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: "{{ vm_name }}"
      register: vm_tools_info
      until:
        - vm_tools_info is not failed
        - vm_tools_info.value.run_state == "RUNNING"
      retries: 10
      delay: 5

    - name: Power on the VM
      vmware.vmware_rest.vcenter_vm_power:
        state: start          
        vm: "{{ vm_name }}"
      
    - name: Pass variables to Ansible controller workflows
      set_stats:
        data:
          vm_name: "{{ vm_name }}"
          vm_cpu: "{{ vm_cpu }}"
          vm_memory: "{{ vm_memory }}"
          vm_disk_size: "{{ vm_disk_size }}"
          vm_datastore: "{{ vm_datastore }}"
