---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name:
    vm_datacenter:
    vm_cluster:
    vm_folder:
    vm_template:
    vm_datastore:
    vm_customization_spec:
    guest_name: "{{ vm_name }}"
    guest_domain:
  tasks:
    - name: Use AAP VMware credentials
      ansible.builtin.set_fact:
        vcenter_server: '{{ lookup("env", "VMWARE_HOST") }}'
        vcenter_user: '{{ lookup("env", "VMWARE_USER") }}'
        vcenter_pass: '{{ lookup("env", "VMWARE_PASSWORD") }}'

    - name: Clone the template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: false
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        datacenter: "{{ vm_datacenter }}"
        folder: "{{ vm_folder }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: default
            datastore: "{{ vm_datastore }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        customization_spec: "{{ vm_customization_spec }}"
        state: poweredon
        wait_for_ip_address: true

    - name: Pass variables to Ansible controller workflows
      ansible.builtin.set_stats:
        data:
          vm_name: "{{ vm_name }}"
          vm_cpu: "{{ vm_cpu }}"
          vm_memory: "{{ vm_memory }}"
          vm_disk_size: "{{ vm_disk_size }}"
          vm_datastore: "{{ vm_datastore }}"
