---
- name: Post configuration of VM
  hosts: "{{ vm_name }}"
  become: true

  tasks:
    - name: Register VM with Red Hat subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"
        consumer_name: "{{ vm_name }}"
        auto_attach: false
        force_register: true

    - name: Enable relevant RHEL8 repos
      community.general.rhsm_repository:
        name: "{{ rhsm_repos }}"
