---
- name: "Post configuration of VM"
  hosts: "{{ vm_name }}" 
  vars:
    rhsm_repos:
        - rhel-8-for-x86_64-baseos-rpms
        - rhel-8-for-x86_64-appstream-rpms
        - ansible-2.9-for-rhel-8-x86_64-rpms
  
  roles:
    - ansible-role-redhat-subscription
      
